### ISSUE TITLE
skid check

### ISSUE THREAD

**Issue by imvast** [mciem/DiscordServerCloner#1]
![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/c30f5e91-5eed-4436-97ae-29c399edd4df)
![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/f3e01642-0772-49f1-85b1-3b3ac5dc505e)
https://terrori.sm/cp/wfjY0LFX
![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/4c7332e8-f018-431f-ba25-fff02a5fe433)

![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/b554689a-8d9e-4abf-be1c-5035134d73f8)

**Comment by mciem** [comment]
so lil bro? learn to read readme "code isn't perfect, it was made for run"

**Comment by imvast** [comment]
> so lil bro? learn to read readme "code isn't perfect, it was made for run"

with my readme LOL so sad . plus idgaf if it was made for fun dont post this dogshit

**Comment by mciem** [comment]
cope retard get off my dick

**Comment by xKiian** [comment]
hey guys! just letting @mciem know that 
![image](https://github.com/mciem/DiscordServerCloner/assets/88455386/e20e4498-1fe0-4ade-a3f3-9789fed758fd)
that part is done automatically by tlsclient :fire:

**Comment by mciem** [comment]
bro said "skid check" who are u to "skid check" aint ur gen aint working? dont u grab customers?

**Comment by mciem** [comment]
> hey guys! just letting @mciem know that 
> 
> ![image](https://github.com/mciem/DiscordServerCloner/assets/88455386/e20e4498-1fe0-4ade-a3f3-9789fed758fd)
> 
> that part is done automatically by tlsclient :fire: 
> 
> 

idgaf

**Comment by imvast** [comment]
> cope retard get off my dick

ur on my dick 24/7 son how about you learn how to code before shit talking

**Comment by imvast** [comment]
aww coping by changing message. ig u are a fem

![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/f695ffc7-3197-4f47-81e2-a1cc78b5eafc)

**Comment by mciem** [comment]
@imvast i love memory leaks in ur code ![image](https://github.com/mciem/DiscordServerCloner/assets/116296625/f2bd1819-1f6b-4c5a-b48e-ff2893649aa6)

**Comment by imvast** [comment]
lil bro showing absolutely nothing 🔥

**Comment by mciem** [comment]
> lil bro showing absolutely nothing 🔥 
> 
> 

never heard of fstrings?

**Comment by imvast** [comment]
if you are talking about this
![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/b1c4d9fe-7c2d-4f27-b8e4-bc50ca9e51c7)

i already changed that long ago but you wouldnt know cuz you cant afford a real gen pooron

**Comment by mciem** [comment]
> if you are talking about this
> 
> ![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/b1c4d9fe-7c2d-4f27-b8e4-bc50ca9e51c7)
> 
> 
> 
> i already changed that long ago but you wouldnt know cuz you cant afford a real gen pooron

i aint buying no ones code since i can do it better

**Comment by imvast** [comment]
> > if you are talking about this
> > ![image](https://user-images.githubusercontent.com/60797067/280139515-b1c4d9fe-7c2d-4f27-b8e4-bc50ca9e51c7.png)
> > i already changed that long ago but you wouldnt know cuz you cant afford a real gen pooron
> 
> i aint buying no ones code since i can do it better

"better" yeah sure u cant even make a simple ass discord cloner without skidding

**Comment by imvast** [comment]
cope

**Comment by imvast** [comment]
![image](https://github.com/mciem/DiscordServerCloner/assets/60797067/d9a638a5-936a-4426-af46-073e63e70596)
awwwww
